name: Build and Commit dist

on:
  push:
    branches:
      - '**'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit dist folder
        run: |
          git add -f dist/ # Force add the 'dist' directory, or specific ignored files
          git commit -m "chore: update dist [skip ci]" --no-verify || echo "No changes to commit"

      - name: Push changes
        run: git push
