name: Build and Commit dist

on:
  push:
    branches:
      - '**'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Commit dist folder
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update dist [skip ci]'
          branch: ${{ github.ref_name }}
          file_pattern: dist/**
          add_options: -f
